spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
          schema_generation:
            create-source: metadata
            script:
              append: true
              target: file:src/main/resources/db/migration/V3__remove_name_from_tests.sql
        format_sql: true
        delimiter: ;
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: src/main/resources/db/migration/V3__remove_name_from_tests.sql
  flyway:
    enabled: false
